eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      # 유레카 서버가 어디에 있는지를 위치 정보를 여기다가 명시해 둔 것이다.
      defaultZone: http://${EUREKA_SERVER_URL}:8761/eureka/

server:
  port: 8080

spring:
  # Redis 설정 추가 (로컬 설정을 기반으로 환경 변수화)
  data:
    redis:
      host: ${REDIS_HOST} # Redis 서버 주소 (환경 변수)
      port: ${REDIS_PORT} # Redis 포트 (환경 변수)
  datasource:
    # MySQL 드라이버 지정
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 도커 컨테이너로 3306 포트로 접속할 수 있도록 띄어놓은 db와 연결
    URL: jdbc:mysql://${DB_HOST}:3306/Glemoa
    username: ${DB_USERNAME} # 환경 변수로 변경
    password: ${DB_PASSWORD} # 환경 변수로 변경
  jpa:
    # 데이터 베이스 플랫폼에는 MySQL DB를 사용할 것이기 때문에 이렇게 설정
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update

# JWT 설정 추가
jwt:
  expiration: ${JWT_EXPIRATION}
  secretKey: ${JWT_SECRET_KEY} # GitHub Secrets에 정의한 변수 이름과 일치시켜야 함
  expirationRt: ${JWT_EXPIRATION_RT}
  secretKeyRt: ${JWT_SECRET_KEY_RT}

logging:
  config: classpath:logback-prod.xml
  level:
    # 기본 레벨을 INFO로 유지 (기타 라이브러리)
    root: INFO

oauth:
  google:
    client-id: 1016866503845-g2stk5ilu15a3i4qj492md1lk85s76v4.apps.googleusercontent.com
    client-secret: ${GOOGLE_CLIENT_SECRET}
    # 이 redirect-uri는 최초에 우리가 설정했던 uri가 어떤 건지를 다시 한번 증명하는 과정임.
    redirect-uri: https://www.glemoa.shop/oauth/google/redirect
  kakao:
    client-id: 4c59ef5dce393223983be904010b1b73
    redirect-uri: https://www.glemoa.shop/oauth/kakao/redirect